Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/Models/Ciutat.cs
using System.ComponentModel.DataAnnotations;

namespace Base_Dades.Models
{
    public class Ciutat
    {
        [Required(ErrorMessage ="El id no pot estar buit")]
        public int id {  get; set; }
        [Required(ErrorMessage = "El nom no pot estar buit")]
        public string name { get; set; } = "";
        [Required(ErrorMessage = "El codi-ciutat no pot estar buit")]
        public string countrycode { get; set; } = "";
        [Required(ErrorMessage = "El districte no pot estar buit")]
        public string district { get; set; } = "";
        [Required(ErrorMessage = "La poblacio no pot estar buit")]
        [Range(1, int.MaxValue, ErrorMessage ="La poblacio no pot ser mes petita que 1")]
        public int population { get; set; }
    }
}

Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/Models/ErrorViewModel.cs
namespace Base_Dades.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/Models/LlenguaPais.cs
namespace Base_Dades.Models
{
    public class LlenguaPais
    {
        public string CountryCode { get; set; }
        public string Language {  get; set; }
        public bool IsOfficial { get; set; }
        public double Pencentage { get; set; }
    }
}

Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/Models/Pais.cs
namespace Base_Dades.Models
{

    public class Pais
    {
        public string? Code { get; set; }
        public string? Name { get; set; }
        public string? Continent { get; set; }
        public string? Region { get; set; }
        public double SurfaceArea { get; set; }
        public int? IndepYear { get; set; }
        public int Population { get; set; }
        public double? Lifeexpectancy { get; set; }
        public double Gnp { get; set; }
        public double? GnpOld { get; set; }
        public string? Localname { get; set; }
        public string? GovernmentForm { get; set; }
        public string? HeadofState { get; set; }
        public int? Capital { get; set; }
        public string? Code2 { get; set; }
    }
}

Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/ViewModels/PaisosCiutats.cs
using Base_Dades.Models;

namespace Base_Dades.ViewModels
{
    public class PaisosCiutats
    {
        public List<Ciutat>? llistaCiutats { get; set; }
        public List<Pais>? llistaPaisos { get; set; }
        public Ciutat? ciutat { get; set; }
        public Pais? pais { get; set; }
    }
}

Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/Controllers/CiutatsController.cs
using Base_Dades.Models;
using Base_Dades.Repository.Interfaces;
using Base_Dades.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Cistell_de_la_compra.Controllers
{
    public class CiutatsController : Controller
    {
        private ICityRepository _cityRepository;
        private ICountryRepository _countryRepository;

        public CiutatsController(ICityRepository pr, ICountryRepository ar)
        {
            this._cityRepository = pr;
            this._countryRepository = ar;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var dades = new PaisosCiutats();
            dades.llistaCiutats = _cityRepository.ObtenirCiutats();
            return View(dades);
        }

        [HttpPost]
        public IActionResult AltaCiutat(PaisosCiutats dades)
        {
            if (!ModelState.IsValid)
            {
                
                dades.llistaPaisos = _countryRepository.obtenirPaisos();
                return View("Afegir",dades);
            }

            _cityRepository.crearCiutat(dades.ciutat);
            TempData["Missatge"] = "La ciutat s'ha creat correctament";
            dades.llistaCiutats = _cityRepository.ObtenirCiutats();

            return View("Index", dades);
        }

        public IActionResult DeleteCiutat(int idCiutatBuscar)
        {
            var dades = new PaisosCiutats();
            _cityRepository.DeleteCiutat(idCiutatBuscar);
            var llistaCiutats = _cityRepository.ObtenirCiutats();
            TempData["Missatge"] = "La ciutat amb id " + idCiutatBuscar + " s'ha eliminat correctament";
            dades.llistaCiutats = llistaCiutats;
            return View("Index", dades);
        }

        public IActionResult UpdateCiutat(int idCiutatBuscar)
        {
                var ciutat = _cityRepository.BuscarCiutat(idCiutatBuscar);
                var paisos = _countryRepository.obtenirPaisos();

            var dades = _countryRepository.paisCiutat(ciutat);
            dades.ciutat = ciutat;
            dades.llistaPaisos = paisos;
                return View("Editar", dades);
        }


        public IActionResult UpdateCiutatFINAL(Ciutat ciutat)
        {
            _cityRepository.Update(ciutat);

            var dades = _countryRepository.paisCiutat(ciutat);

            dades.ciutat = ciutat;

            dades.llistaPaisos = _countryRepository.obtenirPaisos();

            TempData["Missatge"] = "La ciutat s'ha actualitzat correctament";

            return View("Editar", dades);
        }

        [HttpGet]
        public IActionResult Afegir()
        {
            var dades = new PaisosCiutats();
            dades.ciutat = new Ciutat();
            dades.llistaPaisos = _countryRepository.obtenirPaisos();
            return View(dades);
        }
    }
}

Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/Controllers/HomeController.cs
using System.Diagnostics;
using Base_Dades.Models;
using Microsoft.AspNetCore.Mvc;

namespace Base_Dades.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/Views/Ciutats/Afegir.cshtml
@model Base_Dades.ViewModels.PaisosCiutats
<section class="crearCiutat">
	<h1>Crear Ciutat</h1>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <form asp-action="AltaCiutat" method="post">
        <div>
            <label asp-for="ciutat.name"></label>
            <input type="text" asp-for="ciutat.name" class="form-control" />
            <span asp-validation-for="ciutat.name" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="ciutat.countrycode"></label>
            <select asp-for="ciutat.countrycode">
                @foreach (Pais pais in Model.llistaPaisos)
                {
                    <option value="@pais.Code">@pais.Name</option>
                }

            </select>
            <span asp-validation-for="ciutat.countrycode" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="ciutat.district"></label>
            <input type="text" asp-for="ciutat.district" class="form-control" />
            <span asp-validation-for="ciutat.district" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="ciutat.population"></label>
            <input type="number" asp-for="ciutat.population" class="form-control" />
            <span asp-validation-for="ciutat.population" class="text-danger"></span>
        </div>

        <button type="submit">Crear Ciutat</button>
    </form>
</section>

Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/Views/Ciutats/Editar.cshtml
@model Base_Dades.ViewModels.PaisosCiutats
<section>
	<form asp-action="UpdateCiutatFINAL" method="post">
		<table>
			<tr>
				<th>ID</th>
				<th>Nom</th>
				<th>Codi-Pais</th>
				<th>Districte</th>
				<th>Poblacio</th>
			</tr>
			<tr>
				<td>@Model.ciutat.id</td>
				<td><input type="text" asp-for="ciutat.name" value="@Model.ciutat.name" class="form-control" /></td>
				<td>
					<select asp-for="ciutat.countrycode">
						<option value="@Model.ciutat.countrycode">@Model.pais.Name</option>
						@foreach(Pais pais in Model.llistaPaisos){
							<option value="@pais.Code">@pais.Name</option>
						}
						
					</select>
				</td>
				<td><input type="text" asp-for="ciutat.district" value="@Model.ciutat.district" class="form-control" /></td>
				<td><input type="number" asp-for="ciutat.population" value="@Model.ciutat.population" class="form-control" /></td>
			</tr>
		</table>
		<input type="hidden" asp-for="ciutat.id" value="@Model.ciutat.id" />
		<button type="submit">UPDATE</button>
	</form>

	@if (TempData["Missatge"] != null)
	{
		<div style="background-color: #d4edda; padding: 10px; border-radius: 5px; color: #155724;">
			@TempData["Missatge"]
		</div>
	}

	
</section>

Asp.Net.Core/ASP.NET_CORE-Panta-UF-03/Base-Dades/Base-Dades/Views/Ciutats/Index.cshtml
@model Base_Dades.ViewModels.PaisosCiutats


<section class="ciutats">
    <h1>Ciutats del Mon</h1>
    <br /><br /><br /><br /><br />
    @if (TempData["Missatge"] != null)
    {
        <div style="background-color: #d4edda; padding: 10px; border-radius: 5px; color: #155724;">
            @TempData["Missatge"]
        </div>
    }

    

    
    <a asp-action="Afegir" asp-controller="Ciutats" class="btn btn-primary">Afegir Ciutat</a>
    
        <table>
            
                <tr>
                    <th>ID</th>
                    <th>Nom</th>
                    <th>Codi-Pais</th>
                    <th>Districte</th>
                    <th>Poblacio</th>
                </tr>
        @foreach (var el in Model.llistaCiutats)
                {
            <form asp-action="BuscarCiutat" method="post">
                    <tr>
                        <td>@el.id</td>
                        <td>@el.name</td>
                        <td>@el.countrycode</td>
                        <td>@el.district</td>
                        <td>@el.population</td>
                        <input type="hidden" name="idCiutatBuscar" value="@el.id" />
                        <td>
                            <button asp-action="UpdateCiutat" asp-controller="Ciutats" type="submit">Update</button>
                        </td>
                        <td>
                            <button asp-action="DeleteCiutat" asp-controller="Ciutats" type="submit">Delete</button>
                        </td>
                    </tr>
            </form>
                }

        </table>
    
    
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}